"""Adapt web analysis jobs to the bundled pose3d batch pipeline."""

from __future__ import annotations

import os
import importlib.util
import shutil
import sys
from pathlib import Path
from typing import Callable


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def pose3d_project_root() -> Path:
    env_root = os.environ.get("POSE3D_PROJECT_ROOT")
    if env_root:
        candidate = Path(env_root).expanduser()
        if candidate.exists():
            return candidate
    fixed_root = repo_root() / "pose3d_project_2.0_fixed"
    if fixed_root.exists():
        return fixed_root
    raise FileNotFoundError(
        f"未找到固定后端目录: {fixed_root}。请确保 pose3d_project_2.0_fixed 存在，"
        "或通过 POSE3D_PROJECT_ROOT 指定有效目录。"
    )


def default_stereo_params_path() -> Path:
    return pose3d_project_root() / "data" / "session_001" / "stereo_params.json"


def _safe_job_segment(job_id: str) -> str:
    value = str(job_id or "").strip()
    if not value:
        raise ValueError("job_id 不能为空")
    if any(ch in value for ch in ('/', '\\', ':', '*', '?', '"', '<', '>', '|', '\x00')):
        raise ValueError(f"job_id 包含非法路径字符: {job_id!r}")
    if ".." in value:
        raise ValueError(f"job_id 包含非法路径片段: {job_id!r}")
    if value != os.path.basename(value):
        raise ValueError(f"job_id 包含路径分隔符: {job_id!r}")
    return value


def _resolve_pair_dir(pair_out_dir: Path, pair_info: dict[str, object] | None = None) -> Path:
    if pair_info:
        candidate = (
            pair_out_dir
            / str(pair_info.get("group") or "")
            / str(pair_info.get("person") or "")
            / str(pair_info.get("file_stem") or "")
        )
        if candidate.exists():
            return candidate

    preferred = pair_out_dir / "pair_001"
    if preferred.exists():
        return preferred
    candidates = sorted(p.parent for p in pair_out_dir.rglob("pose3d_abs.csv") if p.is_file())
    if len(candidates) == 1:
        return candidates[0]
    if len(candidates) > 1:
        return candidates[0]
    return preferred


def _choose_primary_abs_csv(collect_dir: Path) -> Path:
    candidates = [
        collect_dir / "pose3d_wide_processed.csv",
        collect_dir / "pose3d_abs_zup_ground0.csv",
        collect_dir / "pose3d_abs_filtered_zup_ground0.csv",
        collect_dir / "pose3d_abs_filtered.csv",
        collect_dir / "pose3d_abs.csv",
    ]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        f"未找到可用的 3D CSV，候选: {[str(p) for p in candidates]}"
    )


def write_user_params_py(
    *,
    dest_py: Path,
    data_root: Path,
    output_root: Path,
    groups: list[str],
    log_fn: Callable[[str], None],
    detector_max_frames: int | None = None,
    frame_stride: int = 1,
    temporal_filter_enabled: bool = True,
    temporal_filter_window_size: int = 5,
) -> None:
    settings = build_user_settings(
        data_root=data_root,
        output_root=output_root,
        groups=groups,
        detector_max_frames=detector_max_frames,
        frame_stride=frame_stride,
        temporal_filter_enabled=temporal_filter_enabled,
        temporal_filter_window_size=temporal_filter_window_size,
    )
    pose_root = pose3d_project_root()
    dest_py.parent.mkdir(parents=True, exist_ok=True)
    text = f'''"""Auto-generated by web analysis pipeline."""
from pathlib import Path

PROJECT_ROOT = Path(r"{pose_root.as_posix()}")
DATA_ROOT = Path(r"{data_root.as_posix()}")
OUTPUT_ROOT = Path(r"{output_root.as_posix()}")

SETTINGS = {settings!r}
'''
    dest_py.write_text(text, encoding="utf-8")
    log_fn(f"已写入 pose3d 配置: {dest_py}")


def build_user_settings(
    *,
    data_root: Path,
    output_root: Path,
    groups: list[str],
    detector_max_frames: int | None = None,
    frame_stride: int = 1,
    temporal_filter_enabled: bool = True,
    temporal_filter_window_size: int = 5,
) -> dict[str, object]:
    pose_root = pose3d_project_root()
    model_path = pose_root / "models" / "pose_landmarker_full.task"
    if not model_path.exists():
        raise FileNotFoundError(f"未找到 MediaPipe 模型: {model_path}")
    stride = max(1, int(frame_stride))
    return {
        "input": {
            "data_root": str(data_root),
            "output_root": str(output_root),
            "groups": list(groups),
            "allowed_extensions": [".mp4", ".avi", ".mov", ".mkv"],
        },
        "detector": {
            "method": "mediapipe",
            "person_selection": "highest_conf",
            "max_frames": detector_max_frames,
            "frame_stride": stride,
            "show_pose2d": False,
            "mediapipe": {
                "model_path": str(model_path),
                "output_format": "mediapipe35",
                "min_pose_detection_confidence": 0.4,
                "min_pose_presence_confidence": 0.4,
                "min_tracking_confidence": 0.4,
                "num_poses": 1,
            },
        },
        "video_filter": {"enabled": False},
        "pose2d_vis": {
            "score_threshold": 0.20,
            "draw_skeleton": True,
            "draw_labels": False,
            "draw_frame_index": True,
            "point_radius": 4,
            "line_thickness": 2,
            "codec": "mp4v",
            "save_left": False,
            "save_right": False,
            "save_stereo": False,
        },
        "stereo": {"stereo_mode": "json"},
        "ground_control": {
            "frame_index": 0,
            "distance_m": 2.7,
            "width_m": 2.7,
            "height_m": 2.7,
            "manual_annotation": {
                "reuse_saved_points": True,
                "force_repick": False,
                "use_saved_as_initial_when_repick": True,
                "save_points_json": True,
                "display_scale": 1.0,
                "click_radius_px": 30,
                "show_help": True,
                "window_name_prefix": "ground_control_manual",
            },
            "debug": {"save_debug_images": False},
        },
        "pose3d": {
            "reconstruction_mode": "stereo_triangulation",
            "min_visibility": 0.5,
            "min_presence": 0.5,
            "min_reproj_error_px": None,
            "max_ray_gap_m": 0.30,
            "axis_signs": (1, 1, -1),
            "relative_root_mode": "joint",
            "root_joint_id": None,
            "root_joint_name": "body_com",
        },
        "ground_alignment": {
            "enabled": True,
            "joint_names": [
                "left_heel",
                "right_heel",
                "left_ankle",
                "right_ankle",
                "left_foot_index",
                "right_foot_index",
            ],
            "statistic": "mean",
            "target_z": 0.0,
        },
        "outputs": {
            "save_camera_pose_summary_json": True,
            "save_pose2d_csv": False,
            "save_pose2d_vis_video": False,
            "save_pose3d_abs_csv": True,
            "save_pose3d_relative_csv": False,
            "save_pose3d_abs_ground_aligned_csv": True,
            "save_pose3d_wide_csv": True,
        },
        "paraview_export": {
            "enabled": False,
        },
        "pipeline": {
            "run_sync_check": True,
            "run_build_projection": True,
            "run_pose2d": True,
            "run_pose3d": True,
        },
        "postprocess": {
            "fps": 100.0,
            "coordinate_columns": "auto",
            "final_output_name": "pose3d_wide_processed.csv",
            "outlier": {
                "enabled": bool(temporal_filter_enabled),
                "window_size": max(3, int(temporal_filter_window_size) | 1),
                "mad_k": 3.5,
                "use_scaled_mad": True,
                "min_mad": 1e-6,
                "replace_with_nan": True,
                "skip_columns": [],
            },
            "interpolation": {
                "enabled": bool(temporal_filter_enabled),
                "method": "pchip",
                "max_gap_frames": 25,
                "min_valid_points": 4,
                "inside_only": True,
            },
            "filter": {
                "enabled": bool(temporal_filter_enabled),
                "method": "butterworth",
                "butterworth_order": 4,
                "cutoff_hz": 6.0,
                "savgol_window": max(3, int(temporal_filter_window_size) | 1),
                "savgol_polyorder": 3,
            },
        },
    }


def run_pose3d_pipeline_simple(
    *,
    user_params_path: Path | None = None,
    settings: dict[str, object] | None = None,
    pair_out_dir: Path,
    collect_dir: Path,
    log_fn: Callable[[str], None],
    progress_callback: Callable[[float, str], None] | None = None,
) -> tuple[Path, Path, dict[str, object]]:
    """运行 pipeline 并将 pair 目录下关键 CSV 复制到 collect_dir。"""
    root = pose3d_project_root()
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))

    from pose3d_pkg.cli.run_pipeline import main as run_pipeline_main  # type: ignore

    log_fn("启动 3D 姿态流水线（MediaPipe + 三角化）…")
    run_settings = settings
    if run_settings is None:
        if user_params_path is None:
            raise RuntimeError("缺少运行配置：user_params_path 与 settings 不能同时为空")
        spec = importlib.util.spec_from_file_location("job_user_params", str(user_params_path.resolve()))
        if spec is None or spec.loader is None:
            raise RuntimeError(f"无法加载配置文件: {user_params_path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        run_settings = getattr(module, "SETTINGS", None)
        if not isinstance(run_settings, dict):
            raise RuntimeError(f"配置文件缺少 SETTINGS: {user_params_path}")

    if progress_callback is not None:
        runtime = dict(run_settings.get("_runtime") or {})

        def _pose2d_progress(ratio: float, message: str) -> None:
            progress_callback(max(0.0, min(0.85, float(ratio) * 0.85)), message)

        runtime["pose2d_progress_callback"] = _pose2d_progress
        runtime["pose3d_progress_callback"] = progress_callback
        run_settings = dict(run_settings)
        run_settings["_runtime"] = runtime

    pair_info = dict(run_settings.get("_web_pair_info") or {}) if isinstance(run_settings, dict) else {}
    pair_timings = run_pipeline_main(settings=run_settings) or {}

    pair_dir = _resolve_pair_dir(pair_out_dir, pair_info=pair_info)
    log_fn(f"读取 pair 输出目录: {pair_dir}")
    abs_csv = pair_dir / "pose3d_abs.csv"
    ground0_csv = pair_dir / "pose3d_abs_zup_ground0.csv"
    wide_csv = pair_dir / "pose3d_wide.csv"
    processed_csv = pair_dir / "pose3d_wide_processed.csv"
    if not abs_csv.exists():
        raise FileNotFoundError(f"未生成 pose3d_abs.csv: {abs_csv}")

    collect_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(abs_csv, collect_dir / "pose3d_abs.csv")
    if ground0_csv.exists():
        shutil.copy2(ground0_csv, collect_dir / "pose3d_abs_zup_ground0.csv")
    if wide_csv.exists():
        shutil.copy2(wide_csv, collect_dir / "pose3d_wide.csv")
    if processed_csv.exists():
        shutil.copy2(processed_csv, collect_dir / "pose3d_wide_processed.csv")

    primary = _choose_primary_abs_csv(collect_dir)

    log_fn(f"3D 输出: {primary}")
    pair_metrics: dict[str, object] = {}
    if isinstance(pair_timings, dict):
        pair_name = str(pair_info.get("pair_name") or "")
        pair_metrics = dict(pair_timings.get(pair_name) or {})
    return primary, _choose_primary_abs_csv(collect_dir), pair_metrics


def prepare_batch_job_videos(
    *,
    job_id: str,
    synced_left: Path,
    synced_right: Path,
    data_root: Path,
    stereo_src: Path,
    log_fn: Callable[[str], None],
) -> dict[str, str]:
    person = _safe_job_segment(job_id)
    group = "web_jobs"
    file_stem = "analysis"
    group_dir = data_root / group
    left_dir = group_dir / person / "left"
    right_dir = group_dir / person / "right"
    left_dir.mkdir(parents=True, exist_ok=True)
    right_dir.mkdir(parents=True, exist_ok=True)
    left_dst = left_dir / f"{file_stem}.mp4"
    right_dst = right_dir / f"{file_stem}.mp4"
    shutil.copy2(synced_left, left_dst)
    shutil.copy2(synced_right, right_dst)
    dst_stereo = group_dir / "stereo_params.json"
    if not stereo_src.exists():
        raise FileNotFoundError(f"缺少 stereo_params.json: {stereo_src}")
    shutil.copy2(stereo_src, dst_stereo)
    pair = {
        "group": group,
        "person": person,
        "file_stem": file_stem,
        "pair_name": f"{group}_{person}_{file_stem}",
        "left_video": str(left_dst),
        "right_video": str(right_dst),
        "stereo_params_json": str(dst_stereo),
    }
    log_fn(f"已准备新版 pose3d 批处理输入: {group_dir / person}")
    return pair
