"""Generate per-job settings and run pose3d_pkg.cli.run_pipeline.main."""

from __future__ import annotations

import os
import importlib.util
import shutil
import sys
from pathlib import Path
from typing import Callable


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def pose3d_project_root() -> Path:
    env_root = os.environ.get("POSE3D_PROJECT_ROOT")
    if env_root:
        candidate = Path(env_root).expanduser()
        if candidate.exists():
            return candidate
    fixed_root = repo_root() / "pose3d_project_2.0_fixed"
    if fixed_root.exists():
        return fixed_root
    raise FileNotFoundError(
        f"未找到固定后端目录: {fixed_root}。请确保 pose3d_project_2.0_fixed 存在，"
        "或通过 POSE3D_PROJECT_ROOT 指定有效目录。"
    )


def default_stereo_params_path() -> Path:
    return pose3d_project_root() / "data" / "session_001" / "stereo_params.json"


def _resolve_pair_dir(pair_out_dir: Path) -> Path:
    preferred = pair_out_dir / "pair_001"
    if preferred.exists():
        return preferred
    candidates = sorted(
        p for p in pair_out_dir.glob("pair_*") if p.is_dir()
    )
    if len(candidates) == 1:
        return candidates[0]
    if len(candidates) > 1:
        return candidates[0]
    return preferred


def _choose_primary_abs_csv(collect_dir: Path) -> Path:
    candidates = [
        collect_dir / "pose3d_abs_filtered_zup_ground0.csv",
        collect_dir / "pose3d_abs_filtered.csv",
        collect_dir / "pose3d_abs.csv",
    ]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        f"未找到可用的 3D CSV，候选: {[str(p) for p in candidates]}"
    )


def write_user_params_py(
    *,
    dest_py: Path,
    session_dir: Path,
    stereo_params_json: Path,
    output_dir: Path,
    log_fn: Callable[[str], None],
    detector_max_frames: int | None = None,
    frame_stride: int = 1,
    temporal_filter_enabled: bool = True,
    temporal_filter_window_size: int = 5,
) -> None:
    settings = build_user_settings(
        session_dir=session_dir,
        stereo_params_json=stereo_params_json,
        output_dir=output_dir,
        detector_max_frames=detector_max_frames,
        frame_stride=frame_stride,
        temporal_filter_enabled=temporal_filter_enabled,
        temporal_filter_window_size=temporal_filter_window_size,
    )
    pose_root = pose3d_project_root()
    dest_py.parent.mkdir(parents=True, exist_ok=True)
    text = f'''"""Auto-generated by web analysis pipeline."""
from pathlib import Path

PROJECT_ROOT = Path(r"{pose_root.as_posix()}")
SESSION_DIR = Path(r"{session_dir.as_posix()}")
OUTPUT_DIR = Path(r"{output_dir.as_posix()}")
STEREO_JSON = Path(r"{stereo_params_json.as_posix()}")

SETTINGS = {settings!r}
'''
    dest_py.write_text(text, encoding="utf-8")
    log_fn(f"已写入 pose3d 配置: {dest_py}")


def build_user_settings(
    *,
    session_dir: Path,
    stereo_params_json: Path,
    output_dir: Path,
    detector_max_frames: int | None = None,
    frame_stride: int = 1,
    temporal_filter_enabled: bool = True,
    temporal_filter_window_size: int = 5,
) -> dict[str, object]:
    pose_root = pose3d_project_root()
    model_path = pose_root / "models" / "pose_landmarker_full.task"
    if not model_path.exists():
        raise FileNotFoundError(f"未找到 MediaPipe 模型: {model_path}")
    return {
        "input": {
            "session_dir": str(session_dir),
            "left_prefix": "left",
            "right_prefix": "right",
            "allowed_extensions": [".mp4", ".avi", ".mov", ".mkv"],
            "process_pair_indices": [1],
        },
        "detector": {
            "method": "mediapipe",
            "max_frames": detector_max_frames,
            "frame_stride": max(1, int(frame_stride)),
            "show_pose2d": False,
            "mediapipe": {
                "model_path": str(model_path),
                "output_format": "mediapipe35",
                "min_pose_detection_confidence": 0.4,
                "min_pose_presence_confidence": 0.4,
                "min_tracking_confidence": 0.4,
                "num_poses": 1,
            },
        },
        "video_filter": {"enabled": False},
        "pose2d_vis": {
            "score_threshold": 0.20,
            "draw_skeleton": True,
            "draw_labels": False,
            "draw_frame_index": True,
            "point_radius": 4,
            "line_thickness": 2,
            "codec": "mp4v",
            "save_left": False,
            "save_right": False,
            "save_stereo": False,
        },
        "stereo": {
            "stereo_mode": "json",
            "stereo_params_json": str(stereo_params_json),
        },
        "pose3d": {
            "reconstruction_mode": "stereo_triangulation",
            "min_visibility": 0.5,
            "min_presence": 0.5,
            "min_reproj_error_px": None,
            "max_ray_gap_m": 0.30,
            "axis_signs": (1, 1, -1),
            "relative_root_mode": "joint",
            "root_joint_id": None,
            "root_joint_name": "body_com",
        },
        "temporal_filter": {
            "enabled": bool(temporal_filter_enabled),
            "method": "median_then_mean",
            "window_size": max(1, int(temporal_filter_window_size)),
        },
        "ground_alignment": {
            "enabled": True,
            "joint_names": [
                "left_heel",
                "right_heel",
                "left_ankle",
                "right_ankle",
                "left_foot_index",
                "right_foot_index",
            ],
            "statistic": "median",
            "target_z": 0.0,
            "save_extra_abs_ground_aligned_csv": True,
            "extra_abs_ground_aligned_filename": "pose3d_abs_filtered_zup_ground0.csv",
        },
        "outputs": {
            "output_dir": str(output_dir),
            "save_camera_pose_summary_json": True,
            "save_pose2d_csv": True,
            "save_pose2d_vis_video": False,
            "save_pose3d_abs_csv": True,
            "save_pose3d_relative_csv": True,
            "save_pose3d_abs_filtered_csv": True,
            "save_pose3d_relative_filtered_csv": True,
            "save_pose3d_animation": False,
            "animation_source": "relative",
        },
        "paraview_export": {
            "enabled": False,
        },
        "pipeline": {
            "run_sync_check": True,
            "run_build_projection": True,
            "run_pose2d": True,
            "run_pose3d": True,
            "run_pose3d_animation": False,
        },
    }


def run_pose3d_pipeline_simple(
    *,
    user_params_path: Path | None = None,
    settings: dict[str, object] | None = None,
    pair_out_dir: Path,
    collect_dir: Path,
    log_fn: Callable[[str], None],
    progress_callback: Callable[[float, str], None] | None = None,
) -> tuple[Path, Path, dict[str, object]]:
    """运行 pipeline 并将 pair 目录下关键 CSV 复制到 collect_dir。"""
    root = pose3d_project_root()
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))

    from pose3d_pkg.cli.run_pipeline import main as run_pipeline_main  # type: ignore

    log_fn("启动 3D 姿态流水线（MediaPipe + 三角化）…")
    run_settings = settings
    if run_settings is None:
        if user_params_path is None:
            raise RuntimeError("缺少运行配置：user_params_path 与 settings 不能同时为空")
        spec = importlib.util.spec_from_file_location("job_user_params", str(user_params_path.resolve()))
        if spec is None or spec.loader is None:
            raise RuntimeError(f"无法加载配置文件: {user_params_path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        run_settings = getattr(module, "SETTINGS", None)
        if not isinstance(run_settings, dict):
            raise RuntimeError(f"配置文件缺少 SETTINGS: {user_params_path}")

    if progress_callback is not None:
        runtime = dict(run_settings.get("_runtime") or {})

        def _pose2d_progress(ratio: float, message: str) -> None:
            progress_callback(max(0.0, min(0.85, float(ratio) * 0.85)), message)

        runtime["pose2d_progress_callback"] = _pose2d_progress
        runtime["pose3d_progress_callback"] = progress_callback
        run_settings = dict(run_settings)
        run_settings["_runtime"] = runtime

    pair_timings = run_pipeline_main(settings=run_settings) or {}

    pair_dir = _resolve_pair_dir(pair_out_dir)
    log_fn(f"读取 pair 输出目录: {pair_dir}")
    abs_csv = pair_dir / "pose3d_abs.csv"
    filt_csv = pair_dir / "pose3d_abs_filtered.csv"
    ground0_csv = pair_dir / "pose3d_abs_filtered_zup_ground0.csv"
    if not abs_csv.exists():
        raise FileNotFoundError(f"未生成 pose3d_abs.csv: {abs_csv}")

    collect_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(abs_csv, collect_dir / "pose3d_abs.csv")
    if filt_csv.exists():
        shutil.copy2(filt_csv, collect_dir / "pose3d_abs_filtered.csv")
    else:
        shutil.copy2(abs_csv, collect_dir / "pose3d_abs_filtered.csv")
    if ground0_csv.exists():
        shutil.copy2(ground0_csv, collect_dir / "pose3d_abs_filtered_zup_ground0.csv")

    primary = _choose_primary_abs_csv(collect_dir)

    log_fn(f"3D 输出: {primary}")
    pair_metrics: dict[str, object] = {}
    if isinstance(pair_timings, dict):
        pair_metrics = dict(pair_timings.get("pair_001") or {})
    return primary, _choose_primary_abs_csv(collect_dir), pair_metrics


def prepare_session_videos(
    *,
    synced_left: Path,
    synced_right: Path,
    session_dir: Path,
    stereo_src: Path,
    log_fn: Callable[[str], None],
) -> Path:
    session_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(synced_left, session_dir / "left1.mp4")
    shutil.copy2(synced_right, session_dir / "right1.mp4")
    dst_stereo = session_dir / "stereo_params.json"
    if not stereo_src.exists():
        raise FileNotFoundError(f"缺少 stereo_params.json: {stereo_src}")
    shutil.copy2(stereo_src, dst_stereo)
    log_fn(f"已准备 session 视频与标定: {session_dir}")
    return session_dir
