from .common import (
    MEDIAPIPE_33_CONNECTIONS,
    MEDIAPIPE_33_JOINT_NAMES,
    MEDIAPIPE_35_CONNECTIONS,
    MEDIAPIPE_35_JOINT_NAMES,
    MEDIAPIPE_36_CONNECTIONS,
    MEDIAPIPE_36_JOINT_NAMES,
)
