"""
单位步伐参数列定义（扩展版）

本次重点补充：
- move / restore / unit 的前后、左右、斜向、水平距离
- 轨迹长度、水平轨迹长度、轨迹效率
- 各类腾空时间/次数、步数、步频
- 变向时线速度变化指标
- 膝/踝关节角速度统计
- 踝背屈/跖屈方向化角度统计
"""

import pandas as pd


UNIT_COLUMNS = [
    "unit_id",
    "target_cell",
    "move_start_frame",
    "move_end_frame",
    "restore_start_frame",
    "restore_end_frame",
    "move_duration_s",
    "restore_duration_s",
    "unit_total_duration_s",
    "move_dx_m",
    "move_dy_m",
    "move_dz_m",
    "move_left_right_distance_m",
    "move_front_back_distance_m",
    "move_diagonal_distance_m",
    "move_horizontal_distance_m",
    "move_distance_m",
    "move_direction_type",
    "restore_dx_m",
    "restore_dy_m",
    "restore_dz_m",
    "restore_left_right_distance_m",
    "restore_front_back_distance_m",
    "restore_diagonal_distance_m",
    "restore_horizontal_distance_m",
    "restore_distance_m",
    "restore_direction_type",
    "unit_dx_m",
    "unit_dy_m",
    "unit_dz_m",
    "unit_left_right_distance_m",
    "unit_front_back_distance_m",
    "unit_horizontal_distance_m",
    "unit_total_distance_m",
    "com_path_length_m",
    "com_horizontal_path_length_m",
    "trajectory_efficiency",
    "trajectory_efficiency_xy",
    "move_step_count",
    "restore_step_count",
    "unit_step_count",
    "move_step_frequency_hz",
    "restore_step_frequency_hz",
    "unit_step_frequency_hz",
    "move_mean_com_speed_mps",
    "restore_mean_com_speed_mps",
    "move_peak_com_speed_mps",
    "restore_peak_com_speed_mps",
    "move_direction_change_count",
    "restore_direction_change_count",
    "unit_direction_change_count",
    "move_mean_direction_change_speed_delta_mps",
    "restore_mean_direction_change_speed_delta_mps",
    "unit_mean_direction_change_speed_delta_mps",
    "move_peak_direction_change_speed_delta_mps",
    "restore_peak_direction_change_speed_delta_mps",
    "unit_peak_direction_change_speed_delta_mps",
    "move_mean_direction_change_speed_rate_abs_mps2",
    "restore_mean_direction_change_speed_rate_abs_mps2",
    "unit_mean_direction_change_speed_rate_abs_mps2",
    "move_peak_direction_change_speed_rate_abs_mps2",
    "restore_peak_direction_change_speed_rate_abs_mps2",
    "unit_peak_direction_change_speed_rate_abs_mps2",
    "left_airborne_count",
    "right_airborne_count",
    "left_airborne_time_s",
    "right_airborne_time_s",
    "left_single_airborne_count",
    "right_single_airborne_count",
    "left_single_airborne_time_s",
    "right_single_airborne_time_s",
    "double_airborne_count",
    "double_airborne_time_s",
    "left_knee_max_deg",
    "right_knee_max_deg",
    "left_ankle_max_deg",
    "right_ankle_max_deg",
    "left_knee_min_deg",
    "right_knee_min_deg",
    "left_ankle_min_deg",
    "right_ankle_min_deg",
    "left_knee_mean_abs_angular_velocity_deg_s",
    "right_knee_mean_abs_angular_velocity_deg_s",
    "left_ankle_mean_abs_angular_velocity_deg_s",
    "right_ankle_mean_abs_angular_velocity_deg_s",
    "left_knee_peak_abs_angular_velocity_deg_s",
    "right_knee_peak_abs_angular_velocity_deg_s",
    "left_ankle_peak_abs_angular_velocity_deg_s",
    "right_ankle_peak_abs_angular_velocity_deg_s",
    "left_ankle_sagittal_max_deg",
    "right_ankle_sagittal_max_deg",
    "left_ankle_sagittal_min_deg",
    "right_ankle_sagittal_min_deg",
    "left_ankle_sagittal_range_deg",
    "right_ankle_sagittal_range_deg",
    "left_max_dorsiflexion_deg",
    "right_max_dorsiflexion_deg",
    "left_max_plantarflexion_deg",
    "right_max_plantarflexion_deg",
    "left_ankle_sagittal_mean_abs_angular_velocity_deg_s",
    "right_ankle_sagittal_mean_abs_angular_velocity_deg_s",
    "left_ankle_sagittal_peak_abs_angular_velocity_deg_s",
    "right_ankle_sagittal_peak_abs_angular_velocity_deg_s",
]


def build_unit_metrics_stub() -> pd.DataFrame:
    return pd.DataFrame(columns=UNIT_COLUMNS)
